name: Run Test on BrowserStack

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions@v1.0.3/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: 'bstack-elpais-scraper'
          project-name: 'ElPais Opinion Scraper'
            
      - name: Run tests on BrowserStack
        run: |
           browserstack-sdk python main.py
      
        
